import { useMemo, useState } from 'react'
import { calculateStrategy, calculateYearOne, seasonOne, type Strategy } from './calculations'
const sh=(n:number)=>`Sh ${new Intl.NumberFormat('en-US').format(n)}`
const base:Strategy={name:'Balanced plan',production:50000,milkTons:2.5,milkPrice:20000,yieldPerTon:20000,salesRequest:50000,actualSales:45000,market:5000,rent:17000,transportPerUnit:.1,capacity:72000,maintenance:1800,depreciation:4375,salaries:10000,borrowing:0,interestRate:.1,principalRepayment:0}
const growth:Strategy={...base,name:'Growth plan',production:70000,milkTons:3.5,salesRequest:70000,actualSales:55000,market:9000,rent:15000,transportPerUnit:.2,capacity:120000,maintenance:4700,depreciation:16250,borrowing:30000,principalRepayment:7500}
const labels:Record<keyof Strategy,string>={name:'Option name',production:'Planned production',milkTons:'Milk tonnes',milkPrice:'Milk price / tonne',yieldPerTon:'Yield / tonne',salesRequest:'Sales request',actualSales:'Actual allocated sales',market:'Market investment',rent:'Premise rent',transportPerUnit:'Transport / sold unit',capacity:'Machine capacity',maintenance:'Machine maintenance',depreciation:'Depreciation',salaries:'Fixed salaries',borrowing:'Loan received',interestRate:'Interest rate / season',principalRepayment:'Principal repaid'}
export default function App(){
 const [options,setOptions]=useState([base,growth]); const [recommendation,setRecommendation]=useState(''); const [assumption,setAssumption]=useState('Actual sales allocation from the trainer.')
 const y1=calculateYearOne(seasonOne); const results=useMemo(()=>options.map(o=>calculateStrategy(o,y1.closing)),[options,y1.closing])
 const compareRows: {label:string; get:(r:ReturnType<typeof calculateStrategy>)=>string|number}[]=[
  {label:'Actual sales',get:r=>r.actual},{label:'Revenue',get:r=>sh(r.revenue)},{label:'Unsold units',get:r=>r.unsold},{label:'Net profit',get:r=>sh(r.net)},{label:'Closing cash',get:r=>sh(r.closing)}]
 const change=(i:number,key:keyof Strategy,value:string)=>setOptions(old=>old.map((o,index)=>index===i?{...o,[key]:key==='name'?value:Number(value)||0}:o))
 return <main><header><p className="eyebrow">PORK · GARLIC · ICE CREAM CO.</p><h1>Season 2<br/>decision room</h1><p>Use the verified Season 1 closing cash to test two seasonal plans. Year 2 inputs are estimates until the trainer confirms the rules.</p></header>
 <section className="yearone"><div><p className="eyebrow">Verified Season 1</p><h2>Sh 73,546 closing cash</h2><p>50,000 units × Sh 2 = <b>Sh 100,000 revenue</b>. Sh 110,000 would not match the entered sales and price.</p></div><div className="year-grid"><Metric label="Gross profit" value={sh(y1.gross)}/><Metric label="Net profit" value={sh(y1.net)}/><Metric label="Bonus" value={sh(y1.bonus)}/><Metric label="Tax" value={sh(y1.tax)}/></div></section>
 <section className="options">{options.map((option,i)=>{const r=results[i];return <article className="option" key={i}><div className="option-head"><span>OPTION {String.fromCharCode(65+i)}</span><input aria-label={`Option ${i+1} name`} value={option.name} onChange={e=>change(i,'name',e.target.value)}/></div><div className="option-grid"><div className="inputs">{(Object.keys(labels) as (keyof Strategy)[]).filter(k=>k!=='name').map(k=><label key={k}>{labels[k]}<input type="number" min="0" step={k==='transportPerUnit'||k==='interestRate'?'0.01':'100'} value={option[k] as number} onChange={e=>change(i,k,e.target.value)}/></label>)}</div><div className="result"><p className={r.closing>=0?'safe':'risk'}>{r.closing>=0?'Cash viable':'Cash risk'}</p><h2>{sh(r.closing)}</h2><span>projected closing cash</span><dl><Row a="Revenue" b={sh(r.revenue)}/><Row a="Gross profit" b={sh(r.gross)}/><Row a="Transport" b={sh(r.transport)}/><Row a="Interest" b={sh(r.interest)}/><Row a="Net profit" b={sh(r.net)}/><Row a="Unsold ice cream" b={r.unsold.toLocaleString()}/><Row a="Cash before market" b={sh(r.prepayment)}/></dl>{r.flags.map(f=><p className="flag" key={f}>{f}</p>)}</div></div></article>})}</section>
 <section className="compare"><h2>Decision comparison</h2><table><thead><tr><th></th>{options.map(o=><th key={o.name}>{o.name}</th>)}</tr></thead><tbody>{compareRows.map(row=><tr key={row.label}><td>{row.label}</td>{results.map((r,i)=><td key={i}>{row.get(r)}</td>)}</tr>)}</tbody></table><p className="whatif">What if sales are lower? Reduce “Actual allocated sales” in either option. The table instantly shows lost revenue, additional spoilage, lower profit, and lower closing cash.</p></section>
 <section className="recommend"><h2>Your decision</h2><label>Recommendation<textarea value={recommendation} placeholder="Write the strategy you recommend after comparing the results." onChange={e=>setRecommendation(e.target.value)}/></label><label>Most important assumption<textarea value={assumption} onChange={e=>setAssumption(e.target.value)}/></label></section><footer>All Year 2 values are editable estimates. Check your classroom model before deciding.</footer></main>
}
function Metric({label,value}:{label:string,value:string}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}; function Row({a,b}:{a:string,b:string}){return <div><dt>{a}</dt><dd>{b}</dd></div>}
